version: '3.4'

services:
  ffbox:
    image: ffbox
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app/main/index.cjs"]
